version: "2"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - ./srv:/srv
      - ./filebrowser.db:/database.db
      - ./.filebrowser.json:/.filebrowser.json
    restart: unless-stopped
    user: 
    ports:
      - 12345:80