version: "2"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - ./data:/data
      - ./config:/config
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - 12345:80