[package]
name = "json_rw"
version = "0.1.0"
authors = ["baealex <im@baejino.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-serialize = "0.3"