name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day, on the midnignt
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://blex.me/rss/@baealex"
          description_max_length: "150"
          disable_html_encoding: "true"
          template: "<tr><td><a href=\"$url\">$title ($date)</a></td><td>$description</td></tr>"
          date_format: "yyyy-mm-dd"
